Repository mintapi/mintapi, pull requests merged in 2021-12, with the labels that each got.

#369 release/deploy improvements for pypi
  deploy.sh
  setup.py
Labels: enhancement

#367 Adapt to new css selector for submitting OTP
  mintapi/api.py
Labels: bug

#359 🧹 Convert to the updated categories endpoint
  README.md
  mintapi/api.py
  mintapi/cli.py
  tests/test_driver.py
  tests/test_endpoints_sign_in.py
Labels: enhancement

#370 fix soft token login
  mintapi/api.py
Labels: bug

#366 refactor: :recycle: Split sign in
  mintapi/__init__.py
  mintapi/api.py
  mintapi/cli.py
  mintapi/signIn.py
  tests/test_driver.py
  tests/test_endpoints_sign_in.py
Labels: enhancement

#380 🐛 Initialize attention_msg
  mintapi/cli.py
Labels: bug

#382 ✨ Feature: Export Investment Data to CSV
  mintapi/cli.py
Labels: enhancement, awaiting-feedback
